In [1]:
import pandas as pd
import sklearn
import numpy as np

In [2]:
df=pd.read_csv("./train.csv")

In [3]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
X_train=df[["Pclass","SibSp","Parch"]]
Y_train=df["Survived"].values

In [5]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
X_train = X_train.apply(le.fit_transform)
X_train

     Pclass  SibSp  Parch
0         2      1      0
1         0      1      0
2         2      0      0
3         0      1      0
4         2      0      0
..      ...    ...    ...
886       1      0      0
887       0      0      0
888       2      1      2
889       0      0      0
890       2      0      0

[891 rows x 3 columns]

In [6]:
from sklearn.preprocessing import OneHotEncoder,LabelBinarizer
y = LabelBinarizer().fit_transform(df.Sex)

In [7]:
sex=pd.DataFrame(y,columns=["Sex"])

In [8]:
X_train["Sex"]=sex

In [9]:
X_train

     Pclass  SibSp  Parch  Sex
0         2      1      0    1
1         0      1      0    0
2         2      0      0    0
3         0      1      0    0
4         2      0      0    1
..      ...    ...    ...  ...
886       1      0      0    1
887       0      0      0    0
888       2      1      2    0
889       0      0      0    1
890       2      0      0    1

[891 rows x 4 columns]

In [10]:
age=df['Age'].fillna(float(0)).values

In [11]:
age=age.astype(int)

In [12]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=0, strategy='mean')

In [13]:
age=age.reshape(-1,1)
imp_mean.fit(age)
age=imp_mean.transform(age)

In [14]:
age=age.astype(int)
age=pd.DataFrame(age,columns=["Age"])
X_train["Age"]=age

In [15]:
X_train.head(15)

    Pclass  SibSp  Parch  Sex  Age
0        2      1      0    1   22
1        0      1      0    0   38
2        2      0      0    0   26
3        0      1      0    0   35
4        2      0      0    1   35
5        2      0      0    1   29
6        0      0      0    1   54
7        2      3      1    1    2
8        2      0      2    0   27
9        1      1      0    0   14
10       2      1      1    0    4
11       0      0      0    0   58
12       2      0      0    1   20
13       2      1      5    1   39
14       2      0      0    0   14

# Using Random Forest

In [16]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, n_jobs=-1)
rnd_clf.fit(X_train[:750], Y_train[:750])
# print(X_train.shape,Y_train.shape)

RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, n_jobs=-1)

In [17]:
y_pred_rf = rnd_clf.predict(X_train[750:])

In [18]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_train[750:],y_pred_rf)

0.8297872340425532

# Using AdaBoost

In [19]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
ada_clf = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1), n_estimators=400,algorithm="SAMME.R", learning_rate=0.5)
ada_clf.fit(X_train[:750], Y_train[:750])

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=0.5, n_estimators=400)

In [20]:
y_pred_rf_2 = ada_clf.predict(X_train[750:])

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_train[750:],y_pred_rf_2)

0.8014184397163121

# Using Gradient Boosting

In [22]:
from sklearn.ensemble import GradientBoostingClassifier
gbclf = GradientBoostingClassifier(max_depth=2, n_estimators=5, learning_rate=1.0)
gbclf.fit(X_train[:750], Y_train[:750])

GradientBoostingClassifier(learning_rate=1.0, max_depth=2, n_estimators=5)

In [23]:
y_pred_rf_3 = gbclf.predict(X_train[750:])

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_train[750:],y_pred_rf_3)

0.8439716312056738

## TEST

In [25]:
from sklearn import preprocessing
df1=pd.read_csv("./test.csv")

In [26]:
X_test=df1[["Pclass","SibSp","Parch"]]
le = preprocessing.LabelEncoder()
X_test = X_test.apply(le.fit_transform)
X_test

     Pclass  SibSp  Parch
0         2      0      0
1         2      1      0
2         1      0      0
3         2      0      0
4         2      1      1
..      ...    ...    ...
413       2      0      0
414       0      0      0
415       2      0      0
416       2      0      0
417       2      1      1

[418 rows x 3 columns]

In [27]:
from sklearn.preprocessing import OneHotEncoder,LabelBinarizer
y = LabelBinarizer().fit_transform(df1.Sex)
sex=pd.DataFrame(y,columns=["Sex"])
X_test["Sex"]=sex
X_test

     Pclass  SibSp  Parch  Sex
0         2      0      0    1
1         2      1      0    0
2         1      0      0    1
3         2      0      0    1
4         2      1      1    0
..      ...    ...    ...  ...
413       2      0      0    1
414       0      0      0    0
415       2      0      0    1
416       2      0      0    1
417       2      1      1    1

[418 rows x 4 columns]

In [28]:
age=df['Age'].fillna(float(0)).values
age=age.astype(int)
age=age.reshape(-1,1)
age=imp_mean.transform(age)

In [29]:
age=age.astype(int)
age=pd.DataFrame(age,columns=["Age"])
X_test["Age"]=age

In [30]:
X_test

     Pclass  SibSp  Parch  Sex  Age
0         2      0      0    1   22
1         2      1      0    0   38
2         1      0      0    1   26
3         2      0      0    1   35
4         2      1      1    0   35
..      ...    ...    ...  ...  ...
413       2      0      0    1   29
414       0      0      0    0   44
415       2      0      0    1   29
416       2      0      0    1   34
417       2      1      1    1   18

[418 rows x 5 columns]